services:
  api-node-1:
    image: alpine:latest
    working_dir: /root
    environment:
      - PORT=8080
      - SERVER_NAME=API_NODE_1
    volumes:
      - ./backend:/root
    command: ./app_bin

  api-node-2:
    image: alpine:latest
    working_dir: /root
    environment:
      - PORT=8080
      - SERVER_NAME=API_NODE_2
    volumes:
      - ./backend:/root
    command: ./app_bin

  web-server:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - api-node-1
      - api-node-2
